nexy_slack:
    # The Slack API Incoming WebHooks URL.
    endpoint: '%env(resolve:SLACK_WEBHOOK_ENDPOINT)%'  #you can optionally add resolve as prefix of environment variable to solve parameters things, like %foo%