# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/Atlantic18/DoctrineExtensions/tree/master/doc/
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default: #refer to the default entity manager, some project can actually have multiple entity managers
            sluggable: true   #by configuring this, the bundle is now looking for slug fields on our entities.
            timestampable: true