<?php

namespace App\Security;

use App\Repository\UserRepository;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Guard\AbstractGuardAuthenticator;
use Symfony\Component\Security\Guard\Authenticator\AbstractFormLoginAuthenticator;

//becuase here is for a login form, in order to allow us to do less work, using AbstractFormLoginAuthenticator replacing AbstractGuardAuthenticator
class LoginFormAuthenticator extends AbstractFormLoginAuthenticator
{
    private $userRepository;

    private $router;

    public function __construct(UserRepository $userRepository, RouterInterface $router)
    {
        $this->userRepository = $userRepository;
        $this->router = $router;
    }

    public function supports(Request $request)
    {
        return $request->attributes->get('_route') === 'app_login'
            && $request->isMethod('POST');
    }

    public function getCredentials(Request $request)
    {
//        dd($request->request->all());
//        return[
//            'email' =>$request->request->get('email'),
//            'password' =>$request->request->get('password'),
//        ];

        $credentials = [
            'email' =>$request->request->get('email'),
            'password' =>$request->request->get('password'),
        ];

        $request->getSession()->set(
            Security::LAST_USERNAME,
            $credentials['email']
        );

        return $credentials;
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
//        dd($credentials);
        return $this->userRepository->findOneBy(['email'=>$credentials['email']]);
    }

    public function checkCredentials($credentials, UserInterface $user)
    {
//        dd($user);
        return true;
    }


    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        return new RedirectResponse($this->router->generate('app_homepage'));
    }

    //this is generated by alt+insert to implementing interface method
    protected function getLoginUrl()
    {
        return $this->router->generate('app_login');
    }


}
